//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: setups/setupsapi/setupsapi.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Setupsapi_SetupsClient`, then call methods of this protocol to make API calls.
internal protocol Setupsapi_SetupsClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Setupsapi_SetupsClientInterceptorFactoryProtocol? { get }

  func getSkan(
    _ request: Setupsapi_SkanRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Setupsapi_SkanRequest, Setupsapi_SkanResponse>

  func getOfferings(
    _ request: Setupsapi_OfferingsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Setupsapi_OfferingsRequest, Setupsapi_OfferingsResponse>
}

extension Setupsapi_SetupsClientProtocol {
  internal var serviceName: String {
    return "setupsapi.Setups"
  }

  /// Unary call to GetSkan
  ///
  /// - Parameters:
  ///   - request: Request to send to GetSkan.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getSkan(
    _ request: Setupsapi_SkanRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Setupsapi_SkanRequest, Setupsapi_SkanResponse> {
    return self.makeUnaryCall(
      path: "/setupsapi.Setups/GetSkan",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetSkanInterceptors() ?? []
    )
  }

  /// Unary call to GetOfferings
  ///
  /// - Parameters:
  ///   - request: Request to send to GetOfferings.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getOfferings(
    _ request: Setupsapi_OfferingsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Setupsapi_OfferingsRequest, Setupsapi_OfferingsResponse> {
    return self.makeUnaryCall(
      path: "/setupsapi.Setups/GetOfferings",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetOfferingsInterceptors() ?? []
    )
  }
}

internal protocol Setupsapi_SetupsClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'getSkan'.
  func makeGetSkanInterceptors() -> [ClientInterceptor<Setupsapi_SkanRequest, Setupsapi_SkanResponse>]

  /// - Returns: Interceptors to use when invoking 'getOfferings'.
  func makeGetOfferingsInterceptors() -> [ClientInterceptor<Setupsapi_OfferingsRequest, Setupsapi_OfferingsResponse>]
}

internal final class Setupsapi_SetupsClient: Setupsapi_SetupsClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Setupsapi_SetupsClientInterceptorFactoryProtocol?

  /// Creates a client for the setupsapi.Setups service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Setupsapi_SetupsClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Setupsapi_SetupsProvider: CallHandlerProvider {
  var interceptors: Setupsapi_SetupsServerInterceptorFactoryProtocol? { get }

  func getSkan(request: Setupsapi_SkanRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Setupsapi_SkanResponse>

  func getOfferings(request: Setupsapi_OfferingsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Setupsapi_OfferingsResponse>
}

extension Setupsapi_SetupsProvider {
  internal var serviceName: Substring { return "setupsapi.Setups" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetSkan":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Setupsapi_SkanRequest>(),
        responseSerializer: ProtobufSerializer<Setupsapi_SkanResponse>(),
        interceptors: self.interceptors?.makeGetSkanInterceptors() ?? [],
        userFunction: self.getSkan(request:context:)
      )

    case "GetOfferings":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Setupsapi_OfferingsRequest>(),
        responseSerializer: ProtobufSerializer<Setupsapi_OfferingsResponse>(),
        interceptors: self.interceptors?.makeGetOfferingsInterceptors() ?? [],
        userFunction: self.getOfferings(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Setupsapi_SetupsServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'getSkan'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetSkanInterceptors() -> [ServerInterceptor<Setupsapi_SkanRequest, Setupsapi_SkanResponse>]

  /// - Returns: Interceptors to use when handling 'getOfferings'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetOfferingsInterceptors() -> [ServerInterceptor<Setupsapi_OfferingsRequest, Setupsapi_OfferingsResponse>]
}
