//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: app_install_api.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate Api_IngesterClient, then call methods of this protocol to make API calls.
internal protocol Api_IngesterClientProtocol: GRPCClient {
  func setDevice(
    _ request: Api_DeviceRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_DeviceRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func setAttribution(
    _ request: Api_AttribRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_AttribRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func setTest(
    _ request: Api_TestRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_TestRequest, SwiftProtobuf.Google_Protobuf_Empty>

}

extension Api_IngesterClientProtocol {

  /// Unary call to SetDevice
  ///
  /// - Parameters:
  ///   - request: Request to send to SetDevice.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func setDevice(
    _ request: Api_DeviceRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_DeviceRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: "/api.Ingester/SetDevice",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to SetAttribution
  ///
  /// - Parameters:
  ///   - request: Request to send to SetAttribution.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func setAttribution(
    _ request: Api_AttribRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_AttribRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: "/api.Ingester/SetAttribution",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to SetTest
  ///
  /// - Parameters:
  ///   - request: Request to send to SetTest.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func setTest(
    _ request: Api_TestRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_TestRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: "/api.Ingester/SetTest",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

internal final class Api_IngesterClient: Api_IngesterClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the api.Ingester service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Api_IngesterProvider: CallHandlerProvider {
  func setDevice(request: Api_DeviceRequest, context: StatusOnlyCallContext) -> EventLoopFuture<SwiftProtobuf.Google_Protobuf_Empty>
  func setAttribution(request: Api_AttribRequest, context: StatusOnlyCallContext) -> EventLoopFuture<SwiftProtobuf.Google_Protobuf_Empty>
  func setTest(request: Api_TestRequest, context: StatusOnlyCallContext) -> EventLoopFuture<SwiftProtobuf.Google_Protobuf_Empty>
}

extension Api_IngesterProvider {
  internal var serviceName: Substring { return "api.Ingester" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handleMethod(_ methodName: Substring, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "SetDevice":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.setDevice(request: request, context: context)
        }
      }

    case "SetAttribution":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.setAttribution(request: request, context: context)
        }
      }

    case "SetTest":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.setTest(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

