//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: app_price_api.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate Priceapi_PricerClient, then call methods of this protocol to make API calls.
internal protocol Priceapi_PricerClientProtocol: GRPCClient {
  func getProducts(
    _ request: Priceapi_ProductsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Priceapi_ProductsRequest, Priceapi_ProductsResponse>

  func setPrices(
    _ request: Priceapi_PricesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Priceapi_PricesRequest, SwiftProtobuf.Google_Protobuf_Empty>

}

extension Priceapi_PricerClientProtocol {

  /// Unary call to GetProducts
  ///
  /// - Parameters:
  ///   - request: Request to send to GetProducts.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getProducts(
    _ request: Priceapi_ProductsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Priceapi_ProductsRequest, Priceapi_ProductsResponse> {
    return self.makeUnaryCall(
      path: "/priceapi.Pricer/GetProducts",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to SetPrices
  ///
  /// - Parameters:
  ///   - request: Request to send to SetPrices.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func setPrices(
    _ request: Priceapi_PricesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Priceapi_PricesRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: "/priceapi.Pricer/SetPrices",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

internal final class Priceapi_PricerClient: Priceapi_PricerClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the priceapi.Pricer service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Priceapi_PricerProvider: CallHandlerProvider {
  func getProducts(request: Priceapi_ProductsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Priceapi_ProductsResponse>
  func setPrices(request: Priceapi_PricesRequest, context: StatusOnlyCallContext) -> EventLoopFuture<SwiftProtobuf.Google_Protobuf_Empty>
}

extension Priceapi_PricerProvider {
  internal var serviceName: Substring { return "priceapi.Pricer" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handleMethod(_ methodName: Substring, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "GetProducts":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.getProducts(request: request, context: context)
        }
      }

    case "SetPrices":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.setPrices(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

