//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: app_purchase_api.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate Purchaseapi_IngesterClient, then call methods of this protocol to make API calls.
internal protocol Purchaseapi_IngesterClientProtocol: GRPCClient {
  func setReceipt(
    _ request: Purchaseapi_ReceiptRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Purchaseapi_ReceiptRequest, Purchaseapi_ReceiptResponse>

  func setTransactions(
    _ request: Purchaseapi_TransactionsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Purchaseapi_TransactionsRequest, SwiftProtobuf.Google_Protobuf_Empty>

}

extension Purchaseapi_IngesterClientProtocol {

  /// Unary call to SetReceipt
  ///
  /// - Parameters:
  ///   - request: Request to send to SetReceipt.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func setReceipt(
    _ request: Purchaseapi_ReceiptRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Purchaseapi_ReceiptRequest, Purchaseapi_ReceiptResponse> {
    return self.makeUnaryCall(
      path: "/purchaseapi.Ingester/SetReceipt",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to SetTransactions
  ///
  /// - Parameters:
  ///   - request: Request to send to SetTransactions.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func setTransactions(
    _ request: Purchaseapi_TransactionsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Purchaseapi_TransactionsRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: "/purchaseapi.Ingester/SetTransactions",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

internal final class Purchaseapi_IngesterClient: Purchaseapi_IngesterClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the purchaseapi.Ingester service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Purchaseapi_IngesterProvider: CallHandlerProvider {
  func setReceipt(request: Purchaseapi_ReceiptRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Purchaseapi_ReceiptResponse>
  func setTransactions(request: Purchaseapi_TransactionsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<SwiftProtobuf.Google_Protobuf_Empty>
}

extension Purchaseapi_IngesterProvider {
  internal var serviceName: Substring { return "purchaseapi.Ingester" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handleMethod(_ methodName: Substring, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "SetReceipt":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.setReceipt(request: request, context: context)
        }
      }

    case "SetTransactions":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.setTransactions(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

